#!/usr/bin/env python

import unittest
import os
import subprocess

class S3TestCase(unittest.TestCase):

    def setUp(self):
        self.s3_path = 's3://csync_test'
        proc = subprocess.Popen(['s3cmd', 'mb', self.s3_path], stdout=subprocess.PIPE, stderr=subprocess.PIPE)
        output, errors = proc.communicate()
        if proc.returncode != 0:
            print errors

    def testSync(self):
        self.runInitialSync()
        self.runSubsequentChange()
        self.runEchoMode()
        self.runVerify()

    def runInitialSync(self):
        # Backup data/1 to S3
        self.runS3Command('backup', '', 'data/1')

        # Restore data/1 from S3 to tmp/1
        self.runS3Command('restore', '', 'tmp/1')

        # Verify downloaded content matches what we uploaded
        self.runCommand('diff -r data/1 tmp/1')

    def runSubsequentChange(self):
        # Backup data/2 to S3
        self.runS3Command('backup', '', 'data/2')

        # Restore data/2 from S3 to tmp/2
        self.runS3Command('restore', '', 'tmp/2')

        # Verify downloaded content matches what we uploaded
        self.runCommand('diff -r data/2 tmp/2')

    def runEchoMode(self):
        # Backup data/3 to S3 with Echo mode
        self.runS3Command('backup', '-m echo', 'data/3')

        # Restore data/3 from S3 to tmp/3
        self.runS3Command('restore', '', 'tmp/3')

        # Verify downloaded content matches what we uploaded
        self.runCommand('diff -r data/3 tmp/3')

    def runVerify(self):
        # Modify content on S3 so that it doesn't match the MD5 anymore
        self.runCommand('s3cmd get ' + self.s3_path + '/test/dir_nospace/test tmp/test', False)
        self.runCommand('s3cmd put tmp/test ' + self.s3_path + '/test/file_nospace', False)

        # Backup data/3 to S3 with --verify
        self.runS3Command('backup', '-m echo --verify', 'data/3')

        # Restore data/3 from S3 to tmp/4
        self.runS3Command('restore', '', 'tmp/4')

        # Verify downloaded content matches what we uploaded
        self.runCommand('diff -r data/3 tmp/4')
        pass

    def runS3Command(self, action, extras, local):
        command = '../csync -p testing ' + extras + ' ' + action + ' ' + self.s3_path + '/test ' + local
        self.runCommand(command)

    def runCommand(self, command, validate_output = True):
        command = command.replace("  ", " ")
        command = command.split(" ")
        proc = subprocess.Popen(command, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
        output, errors = proc.communicate()

        if validate_output:
            self.assertEqual(output, "")
            self.assertEqual(errors, "")
        self.assertEqual(proc.returncode, 0)

    def tearDown(self):
        proc = subprocess.Popen(['s3cmd', 'del', '-r', '--force', self.s3_path], stdout=subprocess.PIPE, stderr=subprocess.PIPE)
        output, errors = proc.communicate()
        if proc.returncode != 0:
            print errors

        proc = subprocess.Popen(['s3cmd', 'rb', self.s3_path], stdout=subprocess.PIPE, stderr=subprocess.PIPE)
        output, errors = proc.communicate()
        if proc.returncode != 0:
            print errors

        proc = subprocess.Popen(['rm', '-rf', 'tmp'], stdout=subprocess.PIPE, stderr=subprocess.PIPE)
        output, errors = proc.communicate()
        if proc.returncode != 0:
            print errors

class MantaTestCase(unittest.TestCase):

    def setUp(self):
        self.manta_user = os.environ['MANTA_USER']
        self.manta_path = '/' + self.manta_user + '/stor/csync_test'
        proc = subprocess.Popen(['mmkdir', self.manta_path], stdout=subprocess.PIPE, stderr=subprocess.PIPE)
        output, errors = proc.communicate()
        if proc.returncode != 0:
            print errors

    def testSync(self):
        self.runInitialSync()
        self.runSubsequentChange()
        self.runEchoMode()
        self.runVerify()

    def runInitialSync(self):
        # Backup data/1 to Manta
        self.runMantaCommand('backup', '', 'data/1')

        # Restore data/1 from Manta to tmp/1
        self.runMantaCommand('restore', '', 'tmp/1')

        # Verify downloaded content matches what we uploaded
        self.runCommand('diff -r data/1 tmp/1')

    def runSubsequentChange(self):
        # Backup data/2 to Manta
        self.runMantaCommand('backup', '', 'data/2')

        # Restore data/2 from Manta to tmp/2
        self.runMantaCommand('restore', '', 'tmp/2')

        # Verify downloaded content matches what we uploaded
        self.runCommand('diff -r data/2 tmp/2')

    def runEchoMode(self):
        # Backup data/3 to Manta with Echo mode
        self.runMantaCommand('backup', '-m echo', 'data/3')

        # Restore data/3 from Manta to tmp/3
        self.runMantaCommand('restore', '', 'tmp/3')

        # Verify downloaded content matches what we uploaded
        self.runCommand('diff -r data/3 tmp/3')

    def runVerify(self):
        # Modify content on Manta so that it doesn't match the MD5 anymore
        self.runCommand('mget -o tmp/test ' + self.manta_path + '/test/dir_nospace/test')
        self.runCommand('mput -f tmp/test ' + self.manta_path + '/test/file_nospace')

        # Backup data/3 to Manta with --verify
        self.runMantaCommand('backup', '-m echo --verify', 'data/3')

        # Restore data/3 from Manta to tmp/4
        self.runMantaCommand('restore', '', 'tmp/4')

        # Verify downloaded content matches what we uploaded
        self.runCommand('diff -r data/3 tmp/4')
        pass

    def runMantaCommand(self, action, extras, local):
        command = '../csync -p testing -s manta ' + extras + ' ' + action + ' ' + self.manta_path + '/test ' + local
        self.runCommand(command)

    def runCommand(self, command):
        command = command.replace("  ", " ")
        command = command.split(" ")
        proc = subprocess.Popen(command, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
        output, errors = proc.communicate()

        self.assertEqual(output, "")
        self.assertEqual(errors, "")
        self.assertEqual(proc.returncode, 0)

    def tearDown(self):
        proc = subprocess.Popen(['mrm', '-r', self.manta_path], stdout=subprocess.PIPE, stderr=subprocess.PIPE)
        output, errors = proc.communicate()
        if proc.returncode != 0:
            print errors

        proc = subprocess.Popen(['rm', '-rf', 'tmp'], stdout=subprocess.PIPE, stderr=subprocess.PIPE)
        output, errors = proc.communicate()
        if proc.returncode != 0:
            print errors

if __name__ == '__main__':
    unittest.main()
