#!/usr/bin/env python

# TODO: Remove
import random

import unittest
import os
import subprocess

class S3TestCase(unittest.TestCase):

    def __init__(self, *args, **kwargs):
        unittest.TestCase.__init__(self, *args, **kwargs)
        self.s3_bucket = 's3://csync_test'

    def setUp(self):
        print "S3TestCase::setUp"
        pass

    def tearDown(self):
        print "S3TestCase::tearDown"
        pass

class MantaTestCase(unittest.TestCase):

    def setUp(self):
        self.manta_user = os.environ['MANTA_USER']
        self.manta_path = '/' + self.manta_user + '/stor/csync_test'
        proc = subprocess.Popen(['mmkdir', self.manta_path], stdout=subprocess.PIPE, stderr=subprocess.PIPE)
        output, errors = proc.communicate()
        if proc.returncode != 0:
            print errors

    def testInitialSync(self):
        pass

    def tearDown(self):
        proc = subprocess.Popen(['mrm', '-r', self.manta_path], stdout=subprocess.PIPE, stderr=subprocess.PIPE)
        output, errors = proc.communicate()
        if proc.returncode != 0:
            print errors

if __name__ == '__main__':
    unittest.main()
